/*
 * Songbook API
 * Tourist songs application
 *
 * OpenAPI spec version: 1.5.5
 * Contact: andrzej.przybysz01@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package tech.przybysz.songbook_mobile.api_client.domain;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDateTime;

/**
 * SongAddDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-19T15:40:15.848+01:00")
public class SongAddDTO {
  @SerializedName("addedBy")
  private Long addedBy = null;

  @SerializedName("addedSong")
  private Long addedSong = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("timestamp")
  private LocalDateTime timestamp = null;

  public SongAddDTO addedBy(Long addedBy) {
    this.addedBy = addedBy;
    return this;
  }

   /**
   * Get addedBy
   * @return addedBy
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getAddedBy() {
    return addedBy;
  }

  public void setAddedBy(Long addedBy) {
    this.addedBy = addedBy;
  }

  public SongAddDTO addedSong(Long addedSong) {
    this.addedSong = addedSong;
    return this;
  }

   /**
   * Get addedSong
   * @return addedSong
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getAddedSong() {
    return addedSong;
  }

  public void setAddedSong(Long addedSong) {
    this.addedSong = addedSong;
  }

  public SongAddDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SongAddDTO timestamp(LocalDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public LocalDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(LocalDateTime timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SongAddDTO songAddDTO = (SongAddDTO) o;
    return Objects.equals(this.addedBy, songAddDTO.addedBy) &&
        Objects.equals(this.addedSong, songAddDTO.addedSong) &&
        Objects.equals(this.id, songAddDTO.id) &&
        Objects.equals(this.timestamp, songAddDTO.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addedBy, addedSong, id, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SongAddDTO {\n");
    
    sb.append("    addedBy: ").append(toIndentedString(addedBy)).append("\n");
    sb.append("    addedSong: ").append(toIndentedString(addedSong)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

